# mongodb://root:root123.@localhost:27018

version: '3.8'
services:
  mongo_api:
    image: mongo:latest
    container_name: mongo_api
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123.
    #volumes:
    #  - ./mongo_auth_p:/data/db
    networks:
      - service

networks:
  service:
    driver: bridge
  